version: "3.7"
services:
    database:
        build:
            context: ./database
        command: postgres -c 'max_connections=500'
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
